build_quadtree: constant_bem.cpp ../../src/laplace2d.cpp ../../src/mesh.cpp 
	g++ -O -I../../include -o constant_bem.exe \
		constant_bem.cpp ../../src/laplace2d.cpp ../../src/mesh.cpp
	@echo "Now the example is build, use ./constant_bem.exe <mesh_file> to do the calulation."

